import csv


def list_of_symptoms():
    temp_list = []
    list_symptoms = []

    with open("venv/csv_files/Training Data Symptom Probabilty Distribution Table - Symptom Conditional Probability "
              "Table.csv",
              newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            temp_list.append(row['Symptom'])
            temp_list.append(row['Probability'])
            temp_list.append(row['Not-Symptom'])
            temp_list.append(row['Not-Probability'])

            list_symptoms.append(tuple(temp_list))
            temp_list = []

        return list_symptoms


print(list_of_symptoms())


def list_of_diseases():
    temp_list = []
    list_diseases = []

    with open("venv/csv_files/Training Data Disease Conditional Probabilty Table - Disease Conditional Probability "
              "Table.csv",
              newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            temp_list.append(row['itching'])
            temp_list.append(row['skin_rash'])
            temp_list.append(row['nodal_skin_eruptions'])
            temp_list.append(row['continuous_sneezing'])
            temp_list.append(row['shivering'])
            temp_list.append(row['chills'])
            temp_list.append(row['joint_pain'])
            temp_list.append(row['stomach_pain'])
            temp_list.append(row['acidity'])
            temp_list.append(row['ulcers_on_tongue'])
            temp_list.append(row['muscle_wasting'])
            temp_list.append(row['vomiting'])
            temp_list.append(row['burning_micturition'])
            temp_list.append(row['spotting_ urination'])
            temp_list.append(row['fatigue'])
            temp_list.append(row['weight_gain'])
            temp_list.append(row['anxiety'])
            temp_list.append(row['cold_hands_and_feets'])
            temp_list.append(row['mood_swings'])
            temp_list.append(row['weight_loss'])
            temp_list.append(row['restlessness'])
            temp_list.append(row['lethargy'])
            temp_list.append(row['patches_in_throat'])
            temp_list.append(row['irregular_sugar_level'])
            temp_list.append(row['cough'])
            temp_list.append(row['high_fever'])
            temp_list.append(row['sunken_eyes'])
            temp_list.append(row['breathlessness'])
            temp_list.append(row['sweating'])
            temp_list.append(row['dehydration'])
            temp_list.append(row['indigestion'])
            temp_list.append(row['headache'])
            temp_list.append(row['yellowish_skin'])
            temp_list.append(row['dark_urine'])
            temp_list.append(row['nausea'])
            temp_list.append(row['loss_of_appetite'])
            temp_list.append(row['pain_behind_the_eyes'])
            temp_list.append(row['back_pain'])
            temp_list.append(row['constipation'])
            temp_list.append(row['abdominal_pain'])
            temp_list.append(row['diarrhoea'])
            temp_list.append(row['mild_fever'])
            temp_list.append(row['yellow_urine'])
            temp_list.append(row['yellowing_of_eyes'])
            temp_list.append(row['acute_liver_failure'])
            temp_list.append(row['fluid_overload'])
            temp_list.append(row['swelling_of_stomach'])
            temp_list.append(row['swelled_lymph_nodes'])
            temp_list.append(row['malaise'])
            temp_list.append(row['blurred_and_distorted_vision'])
            temp_list.append(row['phlegm'])
            temp_list.append(row['throat_irritation'])
            temp_list.append(row['redness_of_eyes'])
            temp_list.append(row['sinus_pressure'])
            temp_list.append(row['runny_nose'])
            temp_list.append(row['congestion'])
            temp_list.append(row['chest_pain'])
            temp_list.append(row['weakness_in_limbs'])
            temp_list.append(row['fast_heart_rate'])
            temp_list.append(row['pain_during_bowel_movements'])
            temp_list.append(row['pain_in_anal_region'])
            temp_list.append(row['bloody_stool'])
            temp_list.append(row['irritation_in_anus'])
            temp_list.append(row['neck_pain'])
            temp_list.append(row['dizziness'])
            temp_list.append(row['cramps'])
            temp_list.append(row['bruising'])
            temp_list.append(row['obesity'])
            temp_list.append(row['swollen_legs'])
            temp_list.append(row['swollen_blood_vessels'])
            temp_list.append(row['puffy_face_and_eyes'])
            temp_list.append(row['enlarged_thyroid'])
            temp_list.append(row['brittle_nails'])
            temp_list.append(row['swollen_extremeties'])
            temp_list.append(row['excessive_hunger'])
            temp_list.append(row['extra_marital_contacts'])
            temp_list.append(row['drying_and_tingling_lips'])
            temp_list.append(row['slurred_speech'])
            temp_list.append(row['knee_pain'])
            temp_list.append(row['hip_joint_pain'])
            temp_list.append(row['muscle_weakness'])
            temp_list.append(row['stiff_neck'])
            temp_list.append(row['swelling_joints'])
            temp_list.append(row['movement_stiffness'])
            temp_list.append(row['spinning_movements'])
            temp_list.append(row['loss_of_balance'])
            temp_list.append(row['unsteadiness'])
            temp_list.append(row['weakness_of_one_body_side'])
            temp_list.append(row['loss_of_smell'])
            temp_list.append(row['bladder_discomfort'])
            temp_list.append(row['foul_smell_of urine'])
            temp_list.append(row['continuous_feel_of_urine'])
            temp_list.append(row['passage_of_gases'])
            temp_list.append(row['internal_itching'])
            temp_list.append(row['toxic_look_(typhos)'])
            temp_list.append(row['depression'])
            temp_list.append(row['irritability'])
            temp_list.append(row['muscle_pain'])
            temp_list.append(row['altered_sensorium'])
            temp_list.append(row['red_spots_over_body'])
            temp_list.append(row['belly_pain'])
            temp_list.append(row['abnormal_menstruation'])
            temp_list.append(row['dischromic _patches'])
            temp_list.append(row['watering_from_eyes'])
            temp_list.append(row['increased_appetite'])
            temp_list.append(row['polyuria'])
            temp_list.append(row['family_history'])
            temp_list.append(row['mucoid_sputum'])
            temp_list.append(row['rusty_sputum'])
            temp_list.append(row['lack_of_concentration'])
            temp_list.append(row['visual_disturbances'])
            temp_list.append(row['receiving_blood_transfusion'])
            temp_list.append(row['receiving_unsterile_injections'])
            temp_list.append(row['coma'])
            temp_list.append(row['stomach_bleeding'])
            temp_list.append(row['distention_of_abdomen'])
            temp_list.append(row['history_of_alcohol_consumption'])
            temp_list.append(row['fluid_overload'])
            temp_list.append(row['blood_in_sputum'])
            temp_list.append(row['prominent_veins_on_calf'])
            temp_list.append(row['palpitations'])
            temp_list.append(row['painful_walking'])
            temp_list.append(row['pus_filled_pimples'])
            temp_list.append(row['blackheads'])
            temp_list.append(row['skin_peeling'])
            temp_list.append(row['scurring'])
            temp_list.append(row['silver_like_dusting'])
            temp_list.append(row['small_dents_in_nails'])
            temp_list.append(row['inflammatory_nails'])
            temp_list.append(row['blister'])
            temp_list.append(row['red_sore_around_nose'])
            temp_list.append(row['yellow_crust_ooze'])
            temp_list.append(row['prognosis'])
            temp_list.append(row['Disease Probability'])
            temp_list.append(row['Not Disease Probability'])

            list_diseases.append(tuple(temp_list))
            temp_list = []

        return list_diseases


print(list_of_diseases())
